services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: produser
      POSTGRES_PASSWORD: prodpassword
      POSTGRES_DB: proddb
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  app:
    container_name: packs-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    depends_on:
      - db
    environment:
      NODE_ENV: production
      DATABASE_URL: postgres://produser:prodpassword@db:5432/proddb
      APP_PORT: 8080

volumes:
  pgdata: